[package]
name = "karmaTech"
version = "1.0.0"
authors = []

[addresses]
karmaTech="0x74ff6e72868eddb617f1027f4cac718b2462f36a3b4d1aab4354a5ea0b253d35"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-token-objects'