[package]
name = "karmaTech"
version = "1.0.0"
authors = []

[addresses]
karmaTech="0xf3e10fd929fe8465abb52e23e10794c25c0dcba8ef31e317518c62db71dadb50"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-token-objects'