[package]
name = "karmaTech"
version = "1.0.0"
authors = []

[addresses]
karmaTech="0x30d6b2e46f891f5ce1d0945fa2213ac00d36d307a3ac4e85c6a815a7b522da99"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-token-objects'