[package]
name = "karmaTech"
version = "1.0.0"
authors = []

[addresses]
karmaTech="0xebf8edea620fe20a1d6f2ad5ead3588b2cfad94b5ac1d676eff14bb1e9121efe"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-token-objects'